function mydialog
    d = dialog('Position',[300 500 250 500],'Name','My Dialog');
    Text = {'Aantal mensen:',
          'Aantal mensen types:',
          'Lengte:', 
          'Breedte:', 
          'Blijheidseis:', 
          'Buurtorde:',
          'Random verplaatsen?'
          };
    defaultans = {'40', '2', '8', '8', '1/3', '2'};
    
    aantalmensen = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 350 100 25],...
               'String',Text(1));
  
    am = uicontrol('Parent',d,...
               'Style', 'edit',...
               'Position',[20 330 70 25],...
               'String',defaultans(1),...
               'Callback','delete(gcf)')
           
  aantaltypes = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 300 130 25],...
               'String',Text(2));
  
    at = uicontrol('Parent',d,...
               'Style', 'edit',...
               'Position',[20 280 70 25],...
               'String',defaultans(2),...
               'Callback','delete(gcf)')
   
    lengte = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 250 100 25],...
               'String',Text(3));
  
    lg = uicontrol('Parent',d,...
               'Style', 'edit',...
               'Position',[20 230 70 25],...
               'String',defaultans(3),...
               'Callback','delete(gcf)')
           
    breedte = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 200 100 25],...
               'String',Text(4));
  
    bg = uicontrol('Parent',d,...
               'Style', 'edit',...
               'Position',[20 180 70 25],...
               'String',defaultans(4),...
               'Callback','delete(gcf)')
    
   happy = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 150 100 25],...
               'String',Text(5));
  
    hp = uicontrol('Parent',d,...
               'Style', 'edit',...
               'Position',[20 130 70 25],...
               'String',defaultans(5),...
               'Callback','delete(gcf)')
           
   buurtorde = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[0 100 100 25],...
               'String',Text(6));
  
    bo = uicontrol('Parent',d,...
               'Style', 'edit',...
               'Position',[20 80 70 25],...
               'String',defaultans(6),...
               'Callback','delete(gcf)')
            

    btn = uicontrol('Parent',d,...
               'Position',[10 20 70 25],...
               'String','ok',...
               'Callback','delete(gcf)');
           
 
prompt={'Enter a value of \theta (in degrees)'};
name = 'Theta Value';

options.Interpreter = 'tex';

    %answer = inputdlg(prompt,name,[1 40],defaultans,options);
 

    random = uicontrol('Parent',d,...
               'Style', 'checkbox',...
               'Position',[85 70 70 25],...
               'String','aan',...
               'Callback','delete(gcf)');
    simulatie = uicontrol('Parent',d,...
               'Style', 'checkbox',...
               'Position',[85 50 70 25],...
               'String','Uit',...
               'Callback','delete(gcf)');
end